export const MENS_FOOTWEAR = "MENS_FOOTWEAR";
export const WOMENS_FOOTWEAR = "WOMENS_FOOTWEAR";
export const MENS_CLOTHING = "MENS_CLOTHING";
export const WOMENS_CLOTHING = "WOMENS_CLOTHING";
export const MENS_ACCESSORIES = "MENS_ACCESSORIES";
export const WOMENS_ACCESSORIES = "WOMENS_ACCESSORIES";
export const CHILDREN_ACCESSORIES = "CHILDREN_ACCESSORIES";
